version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: example-application-db
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306" # SET TO AVAILABLE PORT (DEFAULT IS 3306:3306)
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exampledb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

volumes:
  database: